import { Component, ElementRef, ViewChild, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, RouterModule, MatIconModule, MatButtonModule],
  templateUrl: './home.html',
  styleUrl: './home.css',
})
export class HomeComponent {

  @ViewChild('reportContent', { static: false })
  reportContent!: ElementRef;

  public activeTab = signal<string>('clinical');

  benefits = [
    { title: '24/7 Virtual Support', description: 'Our medical assistants are online round-the-clock for help.', icon: 'support_agent', color: 'bg-primary-soft text-primary' },
    { title: 'Expert Consultants', description: 'Connect directly with top specialists across multiple domains.', icon: 'medical_services', color: 'bg-success-soft text-success' },
    { title: 'Instant Booking', description: 'Schedule physical or tele-consultation visits in just a few taps.', icon: 'event_available', color: 'bg-warning-soft text-warning' },
    { title: 'Encrypted Records', description: 'Your medical records (EHR) are protected by HIPAA-compliant security.', icon: 'security', color: 'bg-danger-soft text-danger' }
  ];

  stats = [
    { label: 'Board Doctors', value: '150+' },
    { label: 'Happy Patients', value: '25,000+' },
    { label: 'Consultations', value: '100k+' },
    { label: 'Care Centers', value: '25+' }
  ];

  services = [
    { id: 'clinical', label: 'Clinical Care', icon: 'health_and_safety', title: 'Electronic Health Records & Vitals', desc: 'Real-time entry of patient vitals, medical history, prescriptions, and digital clinical notes for complete electronic health records.', points: ['Live vitals monitoring', 'Secure digital prescriptions', 'Seamless lab & pharmacy sync'] },
    { id: 'billing', label: 'Billing & Finance', icon: 'payments', title: 'Automated Billing & Invoices', desc: 'Manage payment processes, generate instant invoices, and track hospital financial operations smoothly.', points: ['Instant itemized billing', 'Flexible payment options', 'Insurance claim tracking'] },
    { id: 'pharmacy', label: 'Pharmacy & Inventory', icon: 'vaccines', title: 'Smart Inventory & Dispensing', desc: 'Real-time medicine stock tracking, low stock alerts, and quick prescription fulfillment pipelines.', points: ['Automatic stock tracking', 'Direct EHR prescription ingestion', 'Fast checkout queue'] },
    { id: 'telehealth', label: 'Telemedicine', icon: 'videocam', title: 'Virtual Care Anywhere', desc: 'Connect patients to consultants through interactive high-definition video calls directly inside the portal.', points: ['In-app video calls', 'Digital prescription delivery', 'Interactive appointment notes'] }
  ];

  faqs = [
    { question: 'How do I register a new patient?', answer: 'Navigate to the Patient Management tab after logging in as a receptionist or admin, click "Register Patient", and fill out the patient card details.', open: false },
    { question: 'Can doctors view lab reports online?', answer: 'Yes! The clinical care and laboratory modules are synced. All reports generated by the lab technician show up instantly in the patient medical profile.', open: false },
    { question: 'Is the platform accessible on mobile?', answer: 'Absolutely. MEDERP features a responsive grid design, allowing doctors and nurses to update vitals or view reports on tablets and phones.', open: false }
  ];

  toggleFaq(index: number) {
    this.faqs[index].open = !this.faqs[index].open;
  }

  exportPdf() {
    const element = this.reportContent.nativeElement;

    html2canvas(element, { scale: 2 }).then(canvas => {
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = 210;
      const imgWidth = pageWidth - 20;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      pdf.addImage(imgData, 'PNG', 10, 10, imgWidth, imgHeight);
      pdf.save('MEDERP_Homepage_Report.pdf');
    });
  }
}